# Generated by Django 5.2.10 on 2026-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vesselhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='avg_wait_time',
        ),
        migrations.RemoveField(
            model_name='port',
            name='congestion_score',
        ),
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='port',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('analyst', 'Analyst')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='flag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_position_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_position_lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(max_length=50),
        ),
    ]
