# Generated by Django 5.2.10 on 2026-02-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_port_avg_wait_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vesselhistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='port',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='cargo_type',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='imo_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('operator', 'Operator')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='vesselhistory',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('port_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.port')),
                ('port_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel')),
            ],
        ),
    ]
